dist: trusty

language: scala

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

sudo: false

cache:
  directories:
    - $HOME/.m2

before_install:
  - git clone -b travis `git config --get remote.origin.url` target/travis

install: true

script:
  - |
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
      if [ "$TRAVIS_TAG" != "" ]; then
        sbt ++ciBuild
      else
        export CI_RELEASE="$TRAVIS_TAG"

        echo "Version:"
        echo "$VERS"
      fi

      sbt ++ciBuild
    fi
  - |
    if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then
      sbt ++ciBuild
    fi

env:
  global:
    - MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=256m"
    - secure: "gOADOsC+cXcYQVjSAtSP3hNPM/Kw1kqcf/LvxxpyDPrE+GtQbgWjwmD6M63qNx5WHiIvxJQRREsGWTcyiJ/30yAciRC9MRixwNRJCypg6B6W8yCb6gaxN+jze/7d7Sp9H/EyWcHF1784W6SLTjzotSZfScMxYs0KB1T7e07Xmp/l01H7+iurIEyaE0GGk3936d+1QudG9IjEAY2zka9X8ZNhSw0klxFdAsxF6l23TH+RC1Mwd6GjGznSjnQDllT+dSaufpTB/vXdnXUfv2EzaeI0D5XNiWIQ6klZ1mdOyUi5lfWFBTd7TZo32JmwqniDmxsY0w69OAa5mKxMncZWiJtLE8r20LlaCw98pTy4UVtwDPkTYmnv2uyIh9342wNrxPLKfhVa83Q5HaupR9wrWpBo1XMmumm08mBVMNXymeNoHl8hNHpKp/TfMVAsKS56erbEsIUOFDDBobc2QwMlL5aKBpzbyRoReHnA1wdMvVIkIHzX7PqK6vB592e+zVplDcIzUURfIKB6FqSkgOhJZgxj2R2vjamG/OIwO7ckf+3Fizj8ICDrRbDK1yMbLTTlR8U6O89ic2GdnzH40Y++s5vy5jxgVfI+91MSEbxJCBfId9qyOtCJ9lnKZVVg2OWoSItmkqusSkbSFL97qw2Qo/2ec+Ga5ElzdoSwyefftFU="
    - secure: "E8LohpRZNe+6mli6pWcziY3cmf8iQxCmAbNKvg9jdkSMtcLuX3EHB+YPF3sESBQkPv5f4s8gn5C9DwH8OPRM2lcMkSKlsfUQC3ZUVlck2v0P0dz233GdY1M5j6jJdnNbyF2DrzCsbSc4bh6mhGNUrmxWRRWS9Ihuya9IW8nvlJ398aOjGpFdKEDS0uHjjoZ/f0fTgovgHKizF799nOhN1alZjPu/gJyapwdDti2H/8JOPpHZ9lK7FrT7usS3gegdRbQgX4thy4ybRrkhqKFCT4lUUXLzUhbUrlj6cIoXYfM15Dw5wFADFLVOntISc1B33YxVXEMkqtfypH3KtJSwj1IfH2SC4eXNyOb7SEa5Uq3CunAXkNAXomz78aHEdYSfu5S3LCT3u+AYmd//PyDfig3Su31+k0RxoEat994sCUUqKVQFN1Cqw4OJF+EGp3WVrks+Ydey66uxMBJDKMuZIBUL0nmwwZKGpC36wGDMWm6X+FyxrnwcSuXTEPkpG2cBHdiCldb17rWhucBjwzzaCYXFXUORqqj7IrCcSABLEq10tNiUbJVURjftaTSU4zlTQtK9xeQJFzK7ZWIgA+T1MqOux2e39/7a9CP/boSweDbze+Weoji4N2aHkmZjNdBAD/Guk7BGRIJtH1Q7jzc+v8dUHOizeenqjewjHk8pv8s="
    - secure: "kT1VskQUsDfFZwlCE5/RJGrhlIacjD3JA6lZRxjPgVhLz5Zzk/5NBD7HSokA14otNnfTBkCdsT0t8/dd5fSKpPazrq22mQDe85+ahfUChdD0SkHPKM/RCOk0DH/mIs7ms1LXWX14Qz68dPp2R3X6DjmxK8WN27bDvgA7MNkIg2cfSIF6u52dHUKlQNXtvAnod68pZ4FlAshoblGdqQ4p44sa+wwB0o0TToqULq6RyiZIED31DvLED12puhkK2W5CqoLY1oZSJuFSR8KFdW9lxQX4Ww88caIjjVs/CCmLkvvzlgs9Wc0qxvhpNgRWpegbk1KnsJFPlloKQZEFUsoWYBbJbR/bO75niotAufatn9gyDs0mW37Ub6tOMyKc2YLV/0GqOPNiTRv8amFRfkHiYJ5ahFccSNoRZXR4bq3s28yn5Ndk2v1wi6D74lHJJ22iQ/2FIoDvcLjUIPRdcGUsl/rG5ZFyzu6FNxaAckdsoXP6JUIvl37tay61yro2N9XqMxmO3Paezb0FCP7D7NkejQC3nHOXeIOQiZGJRgyndELggZM0kvP23QhGwO0Fkrv/gBr2jxOhRrCLm2E/4dnPR/wzf6VZiJqpo6DsKgDyRXbHywKARnlB/67ICRanLWR+oijn6oh+LIevPDC/QbsuH45fEBUTrTg5x/RnptU+rE8="
